
def gallows(wrong_answer):
    if wrong_answer == 0:
        print("  __")
        print(" |  |")
        print(" |")
        print(" |")
        print(" |")
        print("---")
        print()
    elif wrong_answer == 1:
        print("  __")
        print(" |  |")
        print(" |  o")
        print(" |")
        print(" |")
        print("---")
        print()
    elif wrong_answer == 2:
        print("  __")
        print(" |  |")
        print(" |  o")
        print(" | \\")
        print(" |")
        print("---")
        print()
    elif wrong_answer == 3:
        print("  __")
        print(" |  |")
        print(" |  o")
        print(" | \\|")
        print(" |")
        print("---")
        print()
    elif wrong_answer == 4:
        print("  __")
        print(" |  |")
        print(" |  o")
        print(" | \\|/")
        print(" |")
        print("---")
        print()
    elif wrong_answer == 5:
        print("  __")
        print(" |  |")
        print(" |  o")
        print(" | \\|/")
        print(" | /")
        print("---")
        print()
    elif wrong_answer == 6:
        print("  __")
        print(" |  |")
        print(" |  o")
        print(" | \\|/")
        print(" | / \\")
        print("---")
        print()
    else:
        print("  __")
        print(" |  |")
        print(" |  o")
        print(" | \\|/")
        print(" | / \\")
        print("---")
        print("DEAD")
        print()
